### ISSUE TITLE
特定の一般ユーザーアカウントのコメントが目立つようにして欲しい。

### ISSUE THREAD

**Issue by arigayas** [ys-j/YoutubeLiveChatFlusher#14]
メンバー、モデレーター、チャンネル管理者以外の一般ユーザーアカウントでも、ライブ配信中に特定のアカウントが目立つようになる機能を追加していただきたいです。

具体的には、アニメ「Re:ゼロから始める異世界生活」第3期のラジオ番組（生配信）の際、原作者の方がチャット欄でコメントをされることが多々あります。
しかし、原作者の方は一般ユーザーアカウントでご参加されているため、そのコメントに気づくのが遅れてしまうことがあり、すぐに反応するのが難しい状況です。

このような場合に備え、特定のアカウント名を指定すると、そのアカウントのコメントの「文字の色」や「背景色」、「文字の大きさ」などを設定できる機能を追加していただけると大変助かります。
また、注目したいアカウントが複数ある場合もあるため、リスト形式で指定できるような仕組みを検討いただけるとありがたいです。

現在、コメントの表示方法として「アイコン　名前　本文」が利用可能ですが、
「アイコン　本文」の形式でも可能であれば動作するようにしていただけると嬉しいです。
これにより、コメントの視認性がさらに向上し、効率的に反応できるようになると考えています。

**Comment by ys-j** [comment]
@arigayas さま
コメントありがとうございます。
はじめに、現在帰省中で手元にPCがなく、すぐの対応ができないことをご了承願います。

> 特定のアカウント名を指定すると、そのアカウントのコメントの「文字の色」や「背景色」、「文字の大きさ」などを設定できる機能

取り急ぎ、カスタムCSSで対応できる可能性がありますので、下記の方法をお試しください。
（必要な情報：対象のアカウントの`UC`から始まるチャンネルID）

```css
[data-author-id="UCから始まるチャンネルID1"],
[data-author-id="UCから始まるチャンネルID2"] {
  /* 任意の文字色 */
  color: orange;
  /* 任意の背景色 */
  background-color: rgba(255, 255, 255, .5) !important;
  .name {
    /* 例：アカウント名を非表示にする */
    display: none;
  }
  .body {
    /* 例：コメント本文の文字サイズを1.5倍にする */
    font-size: calc(var(--yt-lcf-font-size) * 1.5);
  }
}
```
※必要に応じて`!important`を指定してください。

なお、UCから始まるチャンネルIDは、チャットのアイコン表示をオンにした状態で、アイコンのリンク先URLに含まれています（`/channel/`以降の文字列）。

> リスト形式で指定できるような仕組み

アカウント別の設定方法については、今後検討させてください。

> 現在、コメントの表示方法として「アイコン　名前　本文」が利用可能ですが、「アイコン　本文」の形式でも可能であれば

ドキュメンテーションの整備が追いついておらず、申し訳ありません。
現在、種類別設定で「アイコン」「名前」「本文」それぞれをクリックすると表示・非表示を切り替えられるようになっています。
その他の要望がありましたら、詳細を教えていただけると対応しやすいです。

**Comment by arigayas** [comment]
@ys-j さま
ご回答いただいたカスタムCSSで無事に対応することができました。ありがとうございます！

> 現在、コメントの表示方法として「アイコン　名前　本文」が利用可能ですが、
> 「アイコン　本文」の形式でも可能であれば動作するようにしていただけると嬉しいです。

説明が不足しており、申し訳ありませんでした。
こちらのコメントは「種類別設定」タブの「通常」の設定が「アイコン　本文」の形式になっている場合でも、
「特定の一般ユーザー」に対して「アイコン　名前　本文」の形式が利用可能になれば嬉しい、という趣旨でした。

ただし、教えていただいたCSSで十分実現可能であることがわかりましたので、
UIにその機能が実装されるアップデートをお待ちしたいと思います。

また、名前を表示したい場合の参考として、以下にメモとして記載しておきます：
``` css
  .name {
    /* 例：アカウント名を表示する */
    display:inline; /* 例：アカウント名を表示する */
  }

```
